# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9980587473b43fb21e2471af31f01b8f53cc93f25a724128f1f22f481ea662a4afff1ce64e75e9a2f15e347031367764c15b1a7519f50486c7d1ceafafd9ad8e

test:
  secret_key_base: d36f9164cae1c20db2d6f924d9d0674b52d958ee0cdd71d5117d8f746ed5e757d4e149d883c0ea11b7a47631b61750cd7e96fdf9308dd52690b4e015ddfc289e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
